++// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAsIRgvze6sUflUFw1mPpg4FsB9GWS8PQ',
    appId: '1:336919319282:web:18906fcf74b395cc89766b',
    messagingSenderId: '336919319282',
    projectId: 'cpmadtest-bcc0f',
    authDomain: 'cpmadtest-bcc0f.firebaseapp.com',
    storageBucket: 'cpmadtest-bcc0f.appspot.com',
    measurementId: 'G-WZ28RKSPV0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKa8m-Ah0QdQxtkU1cGW9fsp_sRLshlWc',
    appId: '1:336919319282:android:503d9eb3d1b3f6fe89766b',
    messagingSenderId: '336919319282',
    projectId: 'cpmadtest-bcc0f',
    storageBucket: 'cpmadtest-bcc0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAikyISv5bKoe5nB2q_9KsMBHWf6owylSc',
    appId: '1:336919319282:ios:35d5348e2aadfdc589766b',
    messagingSenderId: '336919319282',
    projectId: 'cpmadtest-bcc0f',
    storageBucket: 'cpmadtest-bcc0f.appspot.com',
    iosBundleId: 'com.example.notesApp',
  );
}
