// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW1_WuUkKtTCQoUBp9366zy8Z9sUriP8U',
    appId: '1:742536768818:web:498845d87b4fc89220fb2b',
    messagingSenderId: '742536768818',
    projectId: 'exp-9-blog-app',
    authDomain: 'exp-9-blog-app.firebaseapp.com',
    storageBucket: 'exp-9-blog-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYlBgliVzy2hnx1uLxiBDy2Qpy4XRLNTE',
    appId: '1:742536768818:android:e58ec9467a69f87f20fb2b',
    messagingSenderId: '742536768818',
    projectId: 'exp-9-blog-app',
    storageBucket: 'exp-9-blog-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPWHWUWemymZptnCkugrimuwlbeilnFcM',
    appId: '1:742536768818:ios:e0c5ace9c5ea5e8420fb2b',
    messagingSenderId: '742536768818',
    projectId: 'exp-9-blog-app',
    storageBucket: 'exp-9-blog-app.firebasestorage.app',
    iosBundleId: 'com.example.blogApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPWHWUWemymZptnCkugrimuwlbeilnFcM',
    appId: '1:742536768818:ios:e0c5ace9c5ea5e8420fb2b',
    messagingSenderId: '742536768818',
    projectId: 'exp-9-blog-app',
    storageBucket: 'exp-9-blog-app.firebasestorage.app',
    iosBundleId: 'com.example.blogApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBW1_WuUkKtTCQoUBp9366zy8Z9sUriP8U',
    appId: '1:742536768818:web:1bccee1a2d1e887020fb2b',
    messagingSenderId: '742536768818',
    projectId: 'exp-9-blog-app',
    authDomain: 'exp-9-blog-app.firebaseapp.com',
    storageBucket: 'exp-9-blog-app.firebasestorage.app',
  );
}
