// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3Lm26C7ZFTUVbH8X3PSjX1795P0B7S40',
    appId: '1:910114454361:web:931fe3f4ada4612c676a48',
    messagingSenderId: '910114454361',
    projectId: 'assigment-5-expense-manager',
    authDomain: 'assigment-5-expense-manager.firebaseapp.com',
    storageBucket: 'assigment-5-expense-manager.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhko2Z3wHiIA8Zx6MT-inWOY21Bhyghy0',
    appId: '1:910114454361:android:50d615982d014954676a48',
    messagingSenderId: '910114454361',
    projectId: 'assigment-5-expense-manager',
    storageBucket: 'assigment-5-expense-manager.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5lvTc8HgwDm-Jo98MJy_v4yXLSkVz0hY',
    appId: '1:910114454361:ios:254ae6d5bfce697a676a48',
    messagingSenderId: '910114454361',
    projectId: 'assigment-5-expense-manager',
    storageBucket: 'assigment-5-expense-manager.firebasestorage.app',
    iosBundleId: 'com.example.expenseManagerFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5lvTc8HgwDm-Jo98MJy_v4yXLSkVz0hY',
    appId: '1:910114454361:ios:254ae6d5bfce697a676a48',
    messagingSenderId: '910114454361',
    projectId: 'assigment-5-expense-manager',
    storageBucket: 'assigment-5-expense-manager.firebasestorage.app',
    iosBundleId: 'com.example.expenseManagerFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3Lm26C7ZFTUVbH8X3PSjX1795P0B7S40',
    appId: '1:910114454361:web:a5e8fba574167cbb676a48',
    messagingSenderId: '910114454361',
    projectId: 'assigment-5-expense-manager',
    authDomain: 'assigment-5-expense-manager.firebaseapp.com',
    storageBucket: 'assigment-5-expense-manager.firebasestorage.app',
  );
}
